# See https://docs.travis-ci.com/user/languages/r/
# https://stackoverflow.com/questions/39009579/using-r-package-source-files-in-packrat-rather-than-cran-with-travis-ci/39338706#39338706
language: R
# dist: trusty
sudo: false
cache:
  directories: $TRAVIS_BUILD_DIR/packrat/
  packages: true
install:
  - R -e "0" --args --bootstrap-packrat
warnings_are_errors: false
script:
    - Rscript -e 'bookdown::render_book("index.rmd", "all")'
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
    keep-history: false
    local-dir: docs
    target_branch: gh-pages
    verbose: true
